apiVersion: v1
kind: Namespace
metadata:
  name: synapse-matrix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-engine
  namespace: synapse-matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-engine
  template:
    metadata:
      labels:
        app: spark-engine
    spec:
      containers:
      - name: spark-engine
        image: us-central1-docker.pkg.dev/vatom-459619/spark-engine-repo/spark-engine:v7
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: STUDIO_BASE
          value: "https://studio-api.xprize.org"
        - name: PGCONN
          value: "postgresql://sparkuser:h5&epTY*Cnl2@10.9.48.3:5432/spark-engine"
        - name: MATRIX_SERVER_URL
          value: "https://matrix.xprize.org/"
        - name: NODE_ENV
          value: "development"
---
apiVersion: v1
kind: Service
metadata:
  name: spark-engine
  namespace: synapse-matrix
spec:
  selector:
    app: spark-engine
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
